// <auto-generated />
namespace Appointments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Appointments_foreign_keys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Appointments_foreign_keys));
        
        string IMigrationMetadata.Id
        {
            get { return "201610191229208_Appointments_foreign_keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
